version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3308:3306"
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - ../var:/var/www/symfony/var
            - ../vendor:/var/www/symfony/vendor
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - ../var:/var/www/symfony/var
            - ../vendor:/var/www/symfony/vendor
        ports:
            - "8089:80"
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

volumes:
    db_app:

networks:
    symfony_app:
